### ISSUE TITLE
Value in text

### ISSUE THREAD

**Issue by DenisK32** [Lelik13a/Zabbix-GluserFS#6]
I get zabbix exhaust as xml is this ok?
Exhaust:
![Screenshot_3](https://user-images.githubusercontent.com/87809852/126628719-441b9f1b-4559-4457-acc9-7e695d3581bc.png)

**Comment by Lelik13a** [comment]
Yes. Other depended items parse this.

**Comment by DenisK32** [comment]
Understood, thanks!
